url: http://mszk.design/
baseurl: 

# Site settings
title: MSZK
email: your-email@domain.com
description: MSZK est un studio multi-dimensionnel basé à Nantes. Du graphic design au branding en passant par le marketing digital, ce one-man-studio écoute, discute, et crée.

# Team names, titles and social links
people:
- name: Nicolo
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: https://twitter.com/MSZKdesigns
    - title: linkedin
      url: https://www.linkedin.com/in/mszkwz

- name: Mathiey
  pic: 2
  position: Lead Developer
  social:
    - title: twitter
      url: https://twitter.com/DeGraciaMathieu
    - title: linkedin
      url: https://www.linkedin.com/in/mathieu-de-gracia-64984b12a
    - title: github
      url: https://github.com/DeGraciaMathieu

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/MSZKdesigns
  - title: linkedin
    url: https://www.linkedin.com/in/mszkwz/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty